let categorisedScoresOut = null
let percentagesArray = userScores()

/**
 * This function gets the user data and grabs all the percentage scores
 *
 * @returns will return an array of strings of percentage scores and passes it as a param in within a function call for categoriseData
 */
function userScores(){
    let percentagesArray = []
    createUsersObject()
        .then(usersObject => usersObject.data)
        .then(usersData => {
            usersData.forEach(function (element) {
                if (element.percentage !== "")
                    percentagesArray.push(element.percentage)
            })
            categoriseData(percentagesArray)
            console.log(categorisedScoresOut)
            var ctx = document.getElementById('performanceChart').getContext('2d');
            var myChart = new Chart(ctx, {
                type: 'pie',
                data: {
                    labels: ['97+', '70-97', '>70'],
                    datasets: [{
                        label: '# of Votes',
                        data: [10,15,9],
                        backgroundColor: [
                            'rgba(255, 0, 0, .5)',
                            'rgba(0, 255, 0, 0.5)',
                            'rgba(0, 0, 255, 0.5)'
                        ],
                        borderColor: [
                            'rgba(255, 99, 132, 1)',
                            'rgba(54, 162, 235, 1)',
                        ],
                        borderWidth: 1
                    }]
                },

            });
        })
}


/**
 * This function divides user scores into three categories
 *
 * @param userScores is the user percentage scores array generated by the userScores function
 *
 * @returns will return a single array giving the total number of users falling into each score category
 */

function categoriseData(userScores){
    let highscore = 0
    let pass = 0
    let notPass = 0
    userScores.forEach(function (element) {
        if (parseFloat(element) >= 97){
            highscore += 1
        } else if (parseFloat(element) >= 70 && parseFloat(element) < 97) {
            pass += 1
        } else {
            notPass += 1
        }
    })
    let categorisedScores = [highscore, pass, notPass]
    console.log(categorisedScores)
    categorisedScoresOut =  categorisedScores
}

var ctx = document.getElementById('performanceChart');


